before_install:
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install cmake
sudo: true
language: rust
rust:
  - stable
script:
    - cargo build --verbose
    - cargo test --verbose
